### ISSUE TITLE
Fix diagram image in README.md

### ISSUE THREAD

**Issue by stephenlauck** [Jason-Doze/pantera#1]
The image for the diagram is not showing up properly in the README.md.

**Comment by Jason-Doze** [comment]
Had the 2 folders for pantera, cloned the correct one, and pushed the updates. Now have created a new branch for finishing the rest of the homework.

**Comment by jasondoze** [comment]
Had two pantera folders, one had been removed, changed path to markdown for diagram.

**Comment by stephenlauck** [comment]
LGTM
